### ISSUE TITLE
Command line nk-md opens file without styling

### ISSUE THREAD

**Issue by JonaC22** [enkidevs/nk-md#1]
When opening the file as an argument for the command it doesn't load topic styling:

![issue](https://cloud.githubusercontent.com/assets/4080302/23095123/738cf692-f5e3-11e6-85f7-7396d21a1335.png)

But with **drag-and-drop** feature it works perfectly:

![issue-2](https://cloud.githubusercontent.com/assets/4080302/23095125/778e84e0-f5e3-11e6-94d0-283cd2dd2f25.png)

**Comment by mathieudutour** [comment]
I think it's because it cannot find the topic file. what is you cd to the root of the content repo?

**Comment by JonaC22** [comment]
The file `what-is-ruby.md` is located in `/home/jonathan/enki/content/Ruby/Fundamentals`

**Comment by mathieudutour** [comment]
yeah, so if you cd to `/home/jonathan/enki/content/` and run `nk-md Ruby/Fundamentals/what-is-ruby.md`?

**Comment by JonaC22** [comment]
It works fine running from the root of project! I made a PR for improving docs
